### ISSUE TITLE
Examine SNPs and high Fst value loci 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/paper-oly-mbdbs-gen#6]
Loci that have high Fst values (7 outliers) and SNPs - do they overlap with any of my methylation lists? (DMLs, DMGs, Size-associated loci)

**Comment by ksil91** [comment]
The VCF with the 7 outlier SNPs is here:
analyses/2bRAD/HCSS_Afilt32m70_01_pp90_m75_BSouts.vcf

**Comment by ksil91** [comment]
The files with Fst per gene(+-2kb) and per snp are here:
analyses/2bRAD/HCSS_sfsm70_PerGene{Site}Fst.csv

**Comment by laurahspencer** [comment]
The 7 outlier SNPs don't overlap with any DMLs, DMLGs, or size-associated loci (SALs, from MACAU).  This was manually checked using IGV.
